meta_product_name: "Scout"
meta_title: "Scout - the workout you deserve"
meta_description: "Find the personal trainer right for you! We offer the most efficient way to find a personal trainer who helps you achieve your goals."
meta_image: "cover.jpg" # should exist in `app/assets/images/`